### ISSUE TITLE
Error when activating themes

### ISSUE THREAD

**Issue by ideabarn** [hexadog/laravel-theme-installer#1]
Undefined variable: pos

  at vendor/hexadog/laravel-themes-manager/src/ThemesManager.php:139
    135▕                 // normalize module name
    136▕                 $name = str_replace(['-theme', 'theme-'], '', $name);
    137▕                 // Check if $name contains vendor
    138▕                 if (strpos($name, '/') !== false) {
  ➜ 139▕                     **return Str::lower($theme->getName()) === Str::lower(substr($name, $pos + 1, strlen($name)));**
    140▕                 } else {
    141▕                     return $theme->getLowerName() === Str::lower($name);
    142▕                 }
    143▕             });

And the same code is applied also at the above function:

public function has(string $name = null)
    {
        return !is_null($this->themes->first(function ($theme) use ($name) {
            // normalize module name
            $name = str_replace(['-theme', 'theme-'], '', $name);
            // Check if $name contains vendor
            if (strpos($name, '/') !== false) {
                **return Str::lower($theme->getName()) === Str::lower(substr($name, $pos + 1, strlen($name)));**
                ;
            } else {
                return $theme->getLowerName() === Str::lower($name);
            }
        }));
    }

**Comment by gaetan-hexadog** [comment]
Wrong repository.
If you still facing problem please open an issue on the related repository: https://github.com/hexadog/laravel-themes-manager
