### ISSUE TITLE
sample code

### ISSUE THREAD

**Issue by perfectwebtech** [hexadog/laravel-theme-installer#2]
hello

is there any sample code for controller or something multi lanague how i can manage with multiple theme and

controller how it will work with multiple themes any hint or example something  possible ? 

multiple routes etc etc

**Comment by gaetan-hexadog** [comment]
Hello @perfectwebtech,

this package is a composer plugin created to install `laravel-theme` package type outside default `vendor` directory.
It does not manage the theme itself. See our package [hexadog/laravel-themes-manager](https://github.com/hexadog/laravel-themes-manager) for multi-themes management in your laravel application.
