### ISSUE TITLE
Installation error on windows

### ISSUE THREAD

**Issue by gaetan-hexadog** [hexadog/laravel-theme-installer#5]
**Issue first opened by @Control361 here: https://github.com/hexadog/laravel-themes-manager/issues/64**

Hello everyone, everything good?
I'm running the package installation but it's showing an error when installing the hexadog/laravel-theme-installer package.

Data:
- "laravel/framework": "^9.19"
- "php": "^8.0.2",

Could you help me?

Thanks
Samuel Vincenzo

![image](https://github.com/hexadog/laravel-themes-manager/assets/103264405/49b23518-22d1-4dd1-93a7-8340b87f5efd)

**Comment by gaetan-hexadog** [comment]
Hello @Control361 ,

can you try to clear your composer cache with this command : `composer clear-cache` and try again.

**Comment by vincenzotecnology** [comment]
Good morning everything is fine?

Thanks for the answer.

I did as you said and ran `composer clear-cache` it still didn't work.
Follow the print.

![image](https://github.com/hexadog/laravel-theme-installer/assets/100493797/25599987-3f7d-474f-8564-d3c55a051776)

**Comment by gaetan-hexadog** [comment]
The message says there may be two files with different capitalization but I don't find any.
Unforlatunately I don't have access to a windows system to test it.
Can you try to download the package archive from here: https://github.com/hexadog/laravel-theme-installer/archive/refs/tags/v1.0.9.zip and uncompress it to see if you have more details ?

**Comment by gaetan-hexadog** [comment]
Close due to non activity.

Don't hesitate to reopen if needed.
